### ISSUE TITLE
User Story 17: player turns

### ISSUE THREAD

**Issue by joh-dah** [hpi-swa-teaching/TabletopUI#21]
As a user in the combat mode I want the player whose turn it is to be marked in the list and to be the only one who can take action.

- [x] accepted when the player whose turn it is marked in the list.
- [x] accepted when the only player whose action is counted is the player whose turn it is.

**Estimation: x**

**Comment by BraunTom** [comment]
Feinde sollen auch in dieser Liste erscheinen. Der GM soll für sie Würfeln
